// <auto-generated />
namespace TrashCollector2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deletedextrapickup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedextrapickup));
        
        string IMigrationMetadata.Id
        {
            get { return "201902081656330_deleted extra-pickup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
