// <auto-generated />
namespace TrashCollector2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class columnaddedcollector : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnaddedcollector));
        
        string IMigrationMetadata.Id
        {
            get { return "201902081914429_column-added-collector"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
